apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rwatch

resources:
  - 01-namespace.yaml
  - 02-daemonset.yaml
  - 03-service.yaml
  - 04-configmap.yaml
  - 05-rbac.yaml
  - 06-tui-deployment.yaml

images:
  - name: rwatch-agent
    newTag: v0.1.0
  - name: rwatch-tui
    newTag: v0.1.0

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: rwatch
  app.kubernetes.io/version: v0.1.0
